### ISSUE TITLE
Cannot Access Uploads Directory

### ISSUE THREAD

**Issue by banpie** [markjaquith/WordPress-Skeleton#104]
I use deploybot to do the automatic serve setup, after I login into my live wordpress and activate the sync db plugin, I get the error " We require write permissions to the standard WordPress uploads directory. Without this permission exports are unavailable. Please grant 755 permissions on the following directory:/home/wwwroot/default/content/uploads", Even I use ftp to grant 777 to the uploads folder in the content, it still does not work.

**Comment by db306** [comment]
Bit late to the party but you need to create a folder named "shared" in your repo at the same level as /content and /wp folders. Once you've done that, create a folder named content inside and another inside on content named uploads. That's it folks.

**Comment by markjaquith** [comment]
Right, so the proper way to do this is with a symlink. So your deploy process should do:

`ln -s /some/location/for/your/shared shared` (from the docroot). This will create a "symlink" from `shared` to `/some/location/for/your/shared` — which is where you should create an `uploads` directory. Then every time you deploy, the deployment will point `shared` to the real location, and the symlink inside `content/uploads/` will point to that via a double symlinking.
