### ISSUE TITLE
Help Starting

### ISSUE THREAD

**Issue by Jab2870** [markjaquith/WordPress-Skeleton#105]
HI, I was hoping to use this skeleton for a project I am working on but am having some trouble.  I will list the steps I have taken and perhaps someone more noligable than me could tell me where I have gone wrong or perhaps how I fix what I have done.

I have cloned the skeleton to my computer.  I don't want my changes to be pushed back to your skeleton though so I deleted the .git folder so I could re-initialise it.

I did `git init` to re-initialise the git repository.  I linked it to a repository I created on bitbucket.  I staged, committed and pushed everything.

I then did  `git submodule init` and `git submodule update` but I still don't have the  sub modules. In case you are wondering, the .gitmodules file is still present and still has the references to all of the modules I should be getting.

Thanks in advance for any help

**Comment by donnahaynes** [comment]
Hi,
Here is a link to some tutorials on youtube : WordPress and Git: http://www.youtube.com/playlist?list=PLmw3IgYjTuTZazmvA0RcLaeHh-ykTEEzr. I was a total git noob when I first used this skeleton and found these tutorials very helpful. My apologies if they're a bit beginner-ish but they helped me! :)

**Comment by Jab2870** [comment]
Thanks very much.   That helps a lot.
