### ISSUE TITLE
Differences from _s

### ISSUE THREAD

**Issue by ghost** [markjaquith/WordPress-Skeleton#110]
Just curious if having a list of differences from _s would help individuals landing on this boilerplate better understand why they might want to use it. I see you've got some caching stuff in here, for example. Maybe that's something worth highlighting?

https://github.com/Automattic/_s

**Comment by l4ci** [comment]
_s is a starter THEME for wordpress. This is a skeleton for setting up the wordpress core with separation of content, upload and theme/plugin files.

Basically you could use both combined!
