### ISSUE TITLE
Installation failed: Download failed. cURL error 60: SSL certificate problem: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by zagzuggles** [markjaquith/WordPress-Skeleton#112]
Hi There,

I have this strange problem.
I am getting this error while **installing a new plugin**, **while downloading and installing a new theme** and **while updating the WordPress**( i am getting notification to update saying: "_You are using a development version of WordPress. You can update to the latest nightly build automatically_". Though the version is 4.9.6)

Error is: _Installation failed: Download failed. cURL error 60: SSL certificate problem: self signed certificate in certificate chain_

To fix the error few steps that i tried, but did not work:
1. Downloaded the file cacert.pem and kept it in C:\MAMP\bin\php\php7.2.1\extras\ssl\cacert.pem
2. In php.ini file, added code curl.cainfo = "C:\MAMP\bin\php\php7.2.1\extras\ssl\cacert.pem".

PFA screenshots for reference.

Please help!
![image](https://user-images.githubusercontent.com/39521177/40447694-0fc3f28c-5ef1-11e8-8ffa-42d61b04afad.png)

![image](https://user-images.githubusercontent.com/39521177/40447722-276faba6-5ef1-11e8-84ab-49cf4543ecc8.png)

![updating worpress](https://user-images.githubusercontent.com/39521177/40447557-9942d92a-5ef0-11e8-85ec-e283e835e294.png)
Thank you,
Biswajit Kar

**Comment by markjaquith** [comment]
This can’t possibly have anything to do with this repo.

**Comment by suzanacavalcante** [comment]
Opa, não sei se encontrou uma solução para o seu problema. 

Caso não tenha. 
Basta adicionar na ultima linha o bloco de comando abaixo em seu wp-config.php

/**
* Don't verify SSL certificates
*/
add_action( 'http_api_curl', function( $handle ) {
curl_setopt( $handle, CURLOPT_SSL_VERIFYPEER, false );
curl_setopt( $handle, CURLOPT_SSL_VERIFYHOST, false );
});
