### ISSUE TITLE
Nginx [no multi site]

### ISSUE THREAD

**Issue by thesame-** [markjaquith/WordPress-Skeleton#113]
Could anyone provide working nginx configuration for this setup? I have been struggling four couple hours now with no results. I did like to keep wordpress in wp sufolder without adding wp to my urls.

**Comment by ihorvorotnov** [comment]
Nginx configuration doesn't require any special tweaking for this setup to work. Your document root must be the project root path, where `wp-config.php` and `index.php` are located - the latter is an actual entry point for the site. Everything else is WordPress' configuration.

**Comment by thesame-** [comment]
Wordpress kept adding wp to urls, so what i did is  set WP_HOME and WP_SITEURL to domain. But then urls like /wp-admin/install.php was not working. Which seems pretty reasonable as wp-admin is actual folder within wp dir.

**Comment by mathieuhays** [comment]
@thesame-  The constants you mentioned should be set as follows:

```php
define('WP_HOME', 'http://www.your-website.com');
define('WP_SITEURL', 'http://www.your-website.com/wp');
```

**Comment by wp-networks** [comment]
@thesame- @mathieuhays 

...actually, you can set
SITEURL & HOME
`https://www.your-website.com`
and the install script will run fine, as long as you have appropriate rewrite configuration in place already... also, see this: https://core.trac.wordpress.org/ticket/19796#comment:78
