### ISSUE TITLE
Can't Establish php database connection on MAMP

### ISSUE THREAD

**Issue by eckno** [markjaquith/WordPress-Skeleton#114]
![tue oct 16 13-12-40 gmt 01-00 2018](https://user-images.githubusercontent.com/41627372/47015700-823d5f00-d102-11e8-9eaf-8c13048f0910.jpg)
![tue oct 16 13-13-20 gmt 01-00 2018](https://user-images.githubusercontent.com/41627372/47015701-82d5f580-d102-11e8-9e6d-edd9bf08d3d3.jpg)
![tue oct 16 13-03-34 gmt 01-00 2018](https://user-images.githubusercontent.com/41627372/47015702-82d5f580-d102-11e8-8cc3-34a7262a212f.jpg)

I tried establishing a php database connection on my mamp local server but i keep getting error. i have attached my index, config and error page, pls i need a solution.

**Comment by Skadi2k3** [comment]
1. Use the actual code of the repository.
2. Set DB_HOST to localhost
