### ISSUE TITLE
Changing symlinks for media files stored in /shared/

### ISSUE THREAD

**Issue by MagentaShark** [markjaquith/WordPress-Skeleton#115]
Hi all

I am after some more information about how to change media symlinks from the /shared/ folder to another specified folder. I have read the readme file, which suggests using Capistrano to look for symlinks point to /shared/ and then repointing them. I am not familiar with Capistrano, and after some initial research, I'm not really sure where to start.

Any support would be much appreciated.

**Comment by Daisuke-sama** [comment]
hey @floatingtongs 
have you resolved your issue?

**Comment by markjaquith** [comment]
@MagentaShark The proper way to do this is to create a symlink from `/shared/` to some other location. e.g. `ln -s /some/other/location/outside/the/site/root/shared shared`. Now it will look as if that directory exists as `shared` when actually it's somewhere else.
