### ISSUE TITLE
Wordpress Multisite and NGINX Configuration

### ISSUE THREAD

**Issue by tmort** [markjaquith/WordPress-Skeleton#39]
I'm attempting to set up WordPress skeleton in a multisite configuration. WordPress skeleton already places WordPress in a subdirectory (wp by default). I've taken the following steps:
1. git clone WordPress-Skeleton
2. Update Submodules and checkout 3.6.1 tag
3. Setup local-config.php to point to my local DB
4. Install WordPress, set site settings to example.com (site), example.com/wp (WordPress URL)
5. Configured multisite (subdirectory) and configured NGINX to serve the Multisite properly (NGINX config can be found here: https://gist.github.com/tmort/6582961)

Once all of this is configured, I can see that the main site (example.com and example.com/wp/wp-admin) both work. 

I then add a new site to the network. Upon navigating to the site url (example.com/test-network-site) the front-end is broken (style.css, for example, cannot be found at the URL http://example.com/wp/test-network-site/wp-content/themes/twentythirteen/style.css?ver=2013-07-18). When navigating to the wp-admin, I'm in a redirect loop. 

My end goal is to be able to use WordPress Skeleton as a base for the sites I deploy and have the multisite configuration work as it does normally (where example.com is the network main site, example.com/test-network-site is a site within the network, and example.com/test-network-site/wp-admin works as it should). At this point my main question may be is this even possible?

Unsure of how to move forward. Any insight would be greatly appreciated!

**Comment by zanematthew** [comment]
Hi, I've been using WP Skelton with Apache, for several years now. Recently decided to give nginx a try, and of course wanted to use WP Skelton. Thus far I'm stumped with the same issue as the original poster;

1. http://example.com/wp-admin/ (inifinite redirect loop)
1. http://example.com/wp/wp-admin/ (no CSS/JS)

Note, the following URLs do work:

* http://example.com/
* http://example.com/sample-site/
* http://example.com/sample-site/wp-admin/

I should be able to access the primary site as http://example.com/wp-admin/, and not http://example.com/wp/wp-admin/ (with no CSS/JS).

Can anyone point me in the right direction with the below nginx config? Note I am entirely new to ngnix, so any explanation would be greatly appreciated. 

```
server {
    # also use www here
    server_name example.com;

    rewrite_log on;
    
    access_log /var/www/logs/access.log;
    error_log /var/www/logs/error.log;

    root /var/www/public/;
    index index.php;

    # Cache
    set $skip_cache 0;

    # POST requests and urls with a query string should always go to PHP
    if ($request_method = POST) {
        set $skip_cache 1;
    }   
    if ($query_string != "") {
       set $skip_cache 1;
    }   
    
    # Don’t cache uris containing the following segments
    if ($request_uri ~* "/wp-admin/|/xmlrpc.php|wp-.*.php|/feed/|index.php|sitemap(_index)?.xml") {
        set $skip_cache 1;
    }   

    # Don’t use the cache for logged in users or recent commenters
    if ($http_cookie ~* "comment_author|wordpress_[a-f0-9]+|wp-postpass|wordpress_no_cache|wordpress_logged_in") {
        set $skip_cache 1;
    }
    ## End Cache

    location / {
        try_files $uri $uri/ /index.php?$args; 
    }

#    I was playing around with this         
#    rewrite ^/(wp-.*.php)$ /wp$1 last;  
#    rewrite ^/(wp-(content|admin|includes).*) /wp/$1 last;

    # Rewrite multisite '.../wp-.*' and '.../*.php'.
    if (!-e $request_filename) {
        rewrite /wp-admin$ $scheme://$host$uri/ permanent;
        rewrite ^/[_0-9a-zA-Z-]+(/wp-.*) /wp$1 last;
        rewrite ^/[_0-9a-zA-Z-]+(/.*\.php)$ /wp$1 last;
    } 

    location ~ \.php$ {
        
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php5-fpm.sock;
        fastcgi_index index.php;
        include fastcgi_params;
                      
        # Caching (FastCGI) configuration
        fastcgi_cache_bypass $skip_cache;
        fastcgi_no_cache $skip_cache;
        fastcgi_cache WORDPRESS;
        fastcgi_cache_valid 60m;
    }
     
    # Caching (FastCGI) configuration
    location ~ /purge(/.*) {
        fastcgi_cache_purge WORDPRESS "$scheme$request_method$host$1";
    }

}
```

**Comment by ilibilibom** [comment]
There seems to be config example here 
https://www.nginx.com/resources/wiki/start/topics/recipes/wordpress/

**Comment by Daisuke-sama** [comment]
Hi,

I'd like to recommend you following the problem solving method through nginx config. So, you will have the access to all admin panels and network admin panel, as well.

Change your rewrites with following
```
if (!-e $request_filename) {
   rewrite ^/(wp-admin/.*)$ /wp/$1 last;
   rewrite ^/[_0-9a-zA-Z-]+(/wp-admin/.*)$ /wp/$1 last;

   rewrite /wp-admin$ $scheme://$host$uri/ permanent;
	
   rewrite ^/[_0-9a-zA-Z-]+(/wp-includes/.*) /wp/$1 last;
   rewrite ^/(wp-[^/]+\.php)$ /wp/$1 last;
   rewrite ^/[_0-9a-zA-Z-]+(/wp-.*) $1 last;
   rewrite ^/[_0-9a-zA-Z-]+(/.*\.php)$ $1 last;
}
rewrite ^/(wp-includes/.*)$ /wp/$1 last;
```
